/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import bean.Nationalite;
import java.sql.Date;
import javax.swing.JOptionPane;
import static main.Main.getController;

/**
 *
 * @author ATH
 */
public class ProfesseurDialog extends javax.swing.JDialog {

    /**
     * Creates new form Professeur
     *
     * @param parent
     * @param modal
     */
    public ProfesseurDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        control_matricule();
        init_combo_box_nationalite();
    }

    public ProfesseurDialog(java.awt.Frame parent, boolean modal, bean.Professeur professeur) {
        super(parent, modal);
        this.professeur = professeur;
        initComponents();
        control_matricule();
        init_combo_box_nationalite();
        try {
            combo_box_titre.setSelectedItem(this.professeur.getTitre());
            combo_box_sexe.setSelectedItem(this.professeur.getSexe());
            combo_box_nationalite.setSelectedItem(getController().getNationaliteController().get(this.professeur.getId_nationalite()).getNationalite());
            check_box_etat.setSelected(this.professeur.isEtat());
            text_field_diplome.setText(this.professeur.getDiplome());
            text_field_lieu_de_naissance.setText(this.professeur.getLieu_de_naissance());
            text_field_matricule.setText(this.professeur.getMatricule());
            text_field_nom_prenom.setText(this.professeur.getNom_prenom());
            text_field_numero_telephone.setText(this.professeur.getContact());
            password_field_mot_de_passe.setText(this.professeur.getMot_de_passe());
            date_chooser_date_de_naissance.setDate(this.professeur.getDate_de_naissance());
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combo_box_titre = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        text_field_matricule = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_field_nom_prenom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combo_box_sexe = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        date_chooser_date_de_naissance = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        text_field_lieu_de_naissance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        combo_box_nationalite = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        text_field_diplome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        text_field_numero_telephone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        password_field_mot_de_passe = new javax.swing.JPasswordField();
        button_cancel = new javax.swing.JButton();
        button_ok = new javax.swing.JButton();
        check_box_etat = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paramètre enseignant");
        setResizable(false);

        jLabel1.setText("Titre :");

        combo_box_titre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr", "Mme", "Mlle", "Ing", "Dr", "Pr" }));
        combo_box_titre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_box_titreActionPerformed(evt);
            }
        });

        jLabel2.setText("Matricule :");

        text_field_matricule.setEditable(false);
        text_field_matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_matriculeActionPerformed(evt);
            }
        });

        jLabel3.setText("Nom et prénom :");

        jLabel4.setText("Sexe :");

        combo_box_sexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel5.setText("Date de naissance :");

        jLabel6.setText("Lieu de naissance :");

        jLabel7.setText("Nationalité :");

        combo_box_nationalite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Diplôme :");

        jLabel9.setText("N° téléphone :");

        jLabel10.setText("Mot de passe :");

        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        button_ok.setText("OK");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        check_box_etat.setSelected(true);
        check_box_etat.setText("Disponible");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password_field_mot_de_passe)
                            .addComponent(text_field_numero_telephone)
                            .addComponent(text_field_diplome)
                            .addComponent(combo_box_nationalite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_field_lieu_de_naissance)
                            .addComponent(text_field_nom_prenom)
                            .addComponent(date_chooser_date_de_naissance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_field_matricule)
                                    .addComponent(combo_box_titre, 0, 196, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combo_box_sexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(check_box_etat, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_cancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combo_box_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(combo_box_sexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_field_matricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_box_etat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_field_nom_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(date_chooser_date_de_naissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_field_lieu_de_naissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(combo_box_nationalite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_field_diplome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(text_field_numero_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(password_field_mot_de_passe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_cancel)
                    .addComponent(button_ok))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_field_matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_matriculeActionPerformed

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        action_button_ok();
    }//GEN-LAST:event_button_okActionPerformed

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        action_button_cancel();
    }//GEN-LAST:event_button_cancelActionPerformed

    private void combo_box_titreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_box_titreActionPerformed
        control_matricule();
    }//GEN-LAST:event_combo_box_titreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            ProfesseurDialog dialog = new ProfesseurDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    private bean.Professeur professeur;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_ok;
    private javax.swing.JCheckBox check_box_etat;
    private javax.swing.JComboBox<String> combo_box_nationalite;
    private javax.swing.JComboBox<String> combo_box_sexe;
    private javax.swing.JComboBox<String> combo_box_titre;
    private com.toedter.calendar.JDateChooser date_chooser_date_de_naissance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField password_field_mot_de_passe;
    private javax.swing.JTextField text_field_diplome;
    private javax.swing.JTextField text_field_lieu_de_naissance;
    private javax.swing.JTextField text_field_matricule;
    private javax.swing.JTextField text_field_nom_prenom;
    private javax.swing.JTextField text_field_numero_telephone;
    // End of variables declaration//GEN-END:variables
    private void action_button_cancel() {
        dispose();
    }

    private void action_button_ok() {
        if (text_field_matricule.getText().isEmpty() || text_field_nom_prenom.getText().isEmpty() || combo_box_nationalite.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs ", "Champ vide ou manquant !", JOptionPane.WARNING_MESSAGE);
            return;
        }
        java.sql.Date date;
        try {
            date = new Date(date_chooser_date_de_naissance.getDate().getTime());
        } catch (Exception e) {
            date = null;
        }
        Nationalite nationalite = getController().getNationaliteController().get(combo_box_nationalite.getSelectedItem().toString());
        if (professeur == null) {
            if (getController().getProfesseurController().get(text_field_matricule.getText()) != null) {
                JOptionPane.showMessageDialog(this, "Veuillez mettre de nouvelles données ", "Champ existant ou erroné !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            getController().getProfesseurController().add(
                    text_field_matricule.getText(),
                    nationalite.getId(),
                    text_field_nom_prenom.getText(),
                    date,
                    text_field_lieu_de_naissance.getText(),
                    text_field_numero_telephone.getText(),
                    combo_box_titre.getSelectedItem().toString(),
                    text_field_diplome.getText(),
                    check_box_etat.isSelected(),
                    String.copyValueOf(password_field_mot_de_passe.getPassword()),
                    combo_box_sexe.getSelectedItem().toString()
            );
            if (getController().getUserController().get(text_field_matricule.getText(), String.copyValueOf(password_field_mot_de_passe.getPassword())) == null) {
                getController().getUserController().add(text_field_nom_prenom.getText(), text_field_matricule.getText(), String.copyValueOf(password_field_mot_de_passe.getPassword()));
                getController().getDroitController().add(getController().getUserController().get(text_field_matricule.getText(), String.copyValueOf(password_field_mot_de_passe.getPassword())).getId(), false, true, true, true, true, false, false, false);
            }

        } else {
            getController().getProfesseurController().update(
                    professeur.getId(),
                    text_field_matricule.getText(),
                    nationalite.getId(),
                    text_field_nom_prenom.getText(),
                    date,
                    text_field_lieu_de_naissance.getText(),
                    text_field_numero_telephone.getText(),
                    combo_box_titre.getSelectedItem().toString(),
                    text_field_diplome.getText(),
                    check_box_etat.isSelected(),
                    String.copyValueOf(password_field_mot_de_passe.getPassword()),
                    combo_box_sexe.getSelectedItem().toString()
            );
            if (getController().getUserController().get(professeur.getMatricule(), String.copyValueOf(password_field_mot_de_passe.getPassword())) != null) {
                getController().getUserController().update(getController().getUserController().get(professeur.getMatricule(), String.copyValueOf(password_field_mot_de_passe.getPassword())).getId(), text_field_nom_prenom.getText(), text_field_matricule.getText(), String.copyValueOf(password_field_mot_de_passe.getPassword()));
            }
        }
        JOptionPane.showMessageDialog(this, "Opération effectuée avec success ", "Réussie !", JOptionPane.INFORMATION_MESSAGE);
        control_matricule();
        text_field_nom_prenom.setText("");
        //dispose();
    }

    private void control_matricule() {
        if (combo_box_titre.getSelectedIndex() < 0) {
            return;
        }
        int rang = getController().getProfesseurController().gets().size() + 1;
        String matricule = String.format("%03d", rang);
        while (getController().getProfesseurController().get(matricule) != null) {
            rang += 1;
            matricule = String.format("%03d", rang);
        }
        text_field_matricule.setText(matricule);
    }

    private void init_combo_box_nationalite() {
        combo_box_nationalite.removeAllItems();
        getController().getNationaliteController().gets().forEach((i) -> {
            combo_box_nationalite.addItem(i.getNationalite());
        });
    }
}
