/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;

import bean.Droit;
import bean.User;
import javax.swing.JOptionPane;
import static main.Main.getController;
import static main.Main.getDroit;
import static main.Main.getUser;
import static main.Main.isPrimaire;
import static main.Main.setDroit;

/**
 *
 * @author ATH
 */
public class UserDialog extends javax.swing.JDialog {

    /**
     * Creates new form Nationalite
     *
     * @param parent
     * @param modal
     */
    public UserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (isPrimaire()) {
            check_box_s1.setText("T1");
            check_box_s2.setText("T2");
            check_box_s3.setText("T3");
            check_box_s3.setVisible(true);
        } else {
            check_box_s1.setText("S1");
            check_box_s2.setText("S2");
            check_box_s3.setText("S3");
            check_box_s3.setVisible(false);
        }
        setDroit(getController().getDroitController().get(getUser().getId()));
        if (!getDroit().isSuprimer()) {
            check_box_administrateur.setEnabled(false);
            check_box_supression.setEnabled(false);
        }
    }

    public UserDialog(java.awt.Frame parent, boolean modal, User user) {
        super(parent, modal);
        this.user = user;
        initComponents();
        text_field_nom_prenom.setText(this.user.getNom_prenom());
        text_field_login.setText(this.user.getLogin());
        password_field_mot_de_passe.setText("");
        if (isPrimaire()) {
            check_box_s1.setText("Trim. 1");
            check_box_s2.setText("Trim. 2");
            check_box_s3.setText("Trim. 3");
            check_box_s3.setVisible(true);
        } else {
            check_box_s1.setText("S1");
            check_box_s2.setText("S2");
            check_box_s3.setText("S3");
            check_box_s3.setVisible(false);
        }
        setDroit(getController().getDroitController().get(getUser().getId()));
        Droit droit = getController().getDroitController().get(this.user.getId());
        if (droit != null) {
            check_box_administrateur.setSelected(droit.isAdministration());
            check_box_professeur.setSelected(droit.isProfesseur());
            check_box_ajout.setSelected(droit.isAjouter());
            check_box_modification.setSelected(droit.isModifier());
            check_box_supression.setSelected(droit.isSuprimer());
            check_box_s1.setSelected(droit.isS1());
            check_box_s2.setSelected(droit.isS2());
            check_box_s3.setSelected(droit.isS3());
        }
        if (!getDroit().isSuprimer()) {
            password_field_mot_de_passe.setEnabled(false);
            check_box_administrateur.setEnabled(false);
            check_box_supression.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text_field_nom_prenom = new javax.swing.JTextField();
        button_cancel = new javax.swing.JButton();
        button_ok = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        text_field_login = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        password_field_mot_de_passe = new javax.swing.JPasswordField();
        check_box_administrateur = new javax.swing.JCheckBox();
        check_box_professeur = new javax.swing.JCheckBox();
        check_box_ajout = new javax.swing.JCheckBox();
        check_box_modification = new javax.swing.JCheckBox();
        check_box_supression = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        check_box_s1 = new javax.swing.JCheckBox();
        check_box_s2 = new javax.swing.JCheckBox();
        check_box_s3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paramètre user");
        setResizable(false);

        jLabel1.setText("Nom et prénom :");

        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        button_ok.setText("OK");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        jLabel2.setText("Login :");

        jLabel3.setText("Mot de passe :");

        check_box_administrateur.setText("Administrateur");

        check_box_professeur.setText("Professeur");

        check_box_ajout.setText("Ajout");

        check_box_modification.setText("Modification");

        check_box_supression.setForeground(new java.awt.Color(255, 0, 0));
        check_box_supression.setText("Supression");

        jLabel4.setText("Type de compte :");

        jLabel5.setText("Droit :");

        check_box_s1.setText("S1");

        check_box_s2.setText("S2");

        check_box_s3.setText("S3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_field_nom_prenom, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(text_field_login)
                            .addComponent(password_field_mot_de_passe)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(check_box_administrateur)
                                        .addGap(18, 18, 18)
                                        .addComponent(check_box_professeur))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(check_box_ajout)
                                            .addComponent(check_box_s1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(check_box_modification)
                                            .addComponent(check_box_s2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(check_box_s3)
                                            .addComponent(check_box_supression))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_field_nom_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_field_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(password_field_mot_de_passe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_box_administrateur)
                    .addComponent(check_box_professeur)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_box_ajout)
                    .addComponent(check_box_modification)
                    .addComponent(check_box_supression)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_box_s1)
                    .addComponent(check_box_s2)
                    .addComponent(check_box_s3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_cancel)
                    .addComponent(button_ok))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        action_ok_button();
    }//GEN-LAST:event_button_okActionPerformed

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        action_cancel_button();
    }//GEN-LAST:event_button_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            UserDialog dialog = new UserDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    private User user;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_ok;
    private javax.swing.JCheckBox check_box_administrateur;
    private javax.swing.JCheckBox check_box_ajout;
    private javax.swing.JCheckBox check_box_modification;
    private javax.swing.JCheckBox check_box_professeur;
    private javax.swing.JCheckBox check_box_s1;
    private javax.swing.JCheckBox check_box_s2;
    private javax.swing.JCheckBox check_box_s3;
    private javax.swing.JCheckBox check_box_supression;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField password_field_mot_de_passe;
    private javax.swing.JTextField text_field_login;
    private javax.swing.JTextField text_field_nom_prenom;
    // End of variables declaration//GEN-END:variables
    private void action_ok_button() {
        if (text_field_nom_prenom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir le nom et prénom ", "Champ vide ou manquant !", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (text_field_login.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir le login ", "Champ vide ou manquant !", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (user == null) {
            if (getController().getUserController().get(text_field_login.getText(), String.copyValueOf(password_field_mot_de_passe.getPassword())) != null) {
                JOptionPane.showMessageDialog(this, "Veuillez mettre un nouveau login ", "Champ existant ou erroné !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (check_box_professeur.isSelected() && getController().getProfesseurController().get(text_field_login.getText()) == null) {
                JOptionPane.showMessageDialog(this, "Veuillez mettre le n° matricule du professeur dans le champ login ", "Champ existant ou erroné !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            getController().getUserController().add(text_field_nom_prenom.getText(), text_field_login.getText(), String.copyValueOf(password_field_mot_de_passe.getPassword()));
            getController().getDroitController().add(getController().getUserController().get(text_field_login.getText(), String.copyValueOf(password_field_mot_de_passe.getPassword())).getId(), check_box_administrateur.isSelected(), check_box_professeur.isSelected(), check_box_ajout.isSelected(), check_box_modification.isSelected(), check_box_supression.isSelected(), check_box_s1.isSelected(), check_box_s2.isSelected(), check_box_s3.isSelected());

        } else {
            if (check_box_professeur.isSelected() && getController().getProfesseurController().get(text_field_login.getText()) == null) {
                JOptionPane.showMessageDialog(this, "Veuillez mettre le n° matricule du professeur dans le champ login ", "Champ existant ou erroné !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            getController().getUserController().update(user.getId(), text_field_nom_prenom.getText(), text_field_login.getText(), String.copyValueOf(password_field_mot_de_passe.getPassword()));
            getController().getDroitController().update(user.getId(), check_box_administrateur.isSelected(), check_box_professeur.isSelected(), check_box_ajout.isSelected(), check_box_modification.isSelected(), check_box_supression.isSelected(), check_box_s1.isSelected(), check_box_s2.isSelected(), check_box_s3.isSelected());

        }
        JOptionPane.showMessageDialog(this, "Opération effectuée avec success ", "Réussie !", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }

    private void action_cancel_button() {
        dispose();
    }
}
