/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel;

import bean.Classe;
import bean.Cycle;
import bean.EvaluationClasse;
import bean.EvaluationMatiere;
import bean.Matiere;
import bean.MatiereClasse;
import bean.MatiereType;
import bean.Professeur;
import bean.Semestre;
import java.awt.Color;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import static main.Main.getConnection;
import static main.Main.getController;
import static main.Main.getDroit;
import static main.Main.getUser;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ATH
 */
public class NotePanel extends javax.swing.JPanel {

    /**
     * Creates new form Note
     */
    public NotePanel() {
        if (getDroit().isProfesseur()) {
            Professeur professeur = getController().getProfesseurController().get(getUser().getLogin());
            if (professeur != null) {
                id_professeur = professeur.getId();
            } else {
                id_professeur = null;
            }
        } else {
            id_professeur = null;
        }
        id_eleves = new HashMap<>();
        id_matiere_classes = new HashMap<>();
        id_annees = new HashMap<>();
        id_classes = new HashMap<>();
        id_cycles = new HashMap<>();
        id_semestres = new HashMap<>();
        id_matieres = new HashMap<>();
        id_type_matieres = new HashMap<>();
        initComponents();
        model = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "N°", "Nom et prénom", "Interro. N°1", "Interro. N°2", "Interro. N°3", "Interro. N°4", "Moy. Interro.", "Devoir N°1", "Devoir N°2", "Moy. Devoir", "Composition", "Moy. Classe", "Moy. Gen."
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, true, true, true, true, false, true, true, false, true, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        init_model();
        popup();
        if (getDroit().isProfesseur()) {
            combo_box_annee.setEnabled(false);
            button_bulletin_classe.setEnabled(false);
            menu_item_imprimer.setEnabled(false);
            btn_calculer.setEnabled(false);

        }
        init_combo_box_annee();
        init_combo_box_semestre();
        init_combo_box_cycle();
        init_combo_box_classe();
        init_combo_box_type_matiere();
        init_combo_box_matiere();
        table_note();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_menu = new javax.swing.JPopupMenu();
        menu_item_imprimer = new javax.swing.JMenuItem();
        scroll_pane_table_note = new javax.swing.JScrollPane();
        table_note = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        combo_box_annee = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combo_box_cycle = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo_box_classe = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        combo_box_type_matiere_classe = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        combo_box_matiere = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        combo_box_semestre = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        button_bulletin_classe = new javax.swing.JButton();
        btn_actualiser_table = new javax.swing.JButton();
        btn_calculer = new javax.swing.JButton();

        menu_item_imprimer.setText("Imprimer bulletin");
        menu_item_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_imprimerActionPerformed(evt);
            }
        });
        popup_menu.add(menu_item_imprimer);

        setPreferredSize(new java.awt.Dimension(952, 550));

        table_note.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "Nom et prénom", "Interro. N°1", "Interro. N°2", "Interro. N°3", "Interro. N°4", "Moy. Interro", "Devoir N°1", "Devoir N°2", "Moy. devoir", "Moy. classe", "Composition", "Moy. géné."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, false, true, true, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scroll_pane_table_note.setViewportView(table_note);
        if (table_note.getColumnModel().getColumnCount() > 0) {
            table_note.getColumnModel().getColumn(0).setPreferredWidth(35);
            table_note.getColumnModel().getColumn(0).setMaxWidth(35);
            table_note.getColumnModel().getColumn(2).setPreferredWidth(75);
            table_note.getColumnModel().getColumn(2).setMaxWidth(100);
            table_note.getColumnModel().getColumn(3).setPreferredWidth(75);
            table_note.getColumnModel().getColumn(3).setMaxWidth(100);
            table_note.getColumnModel().getColumn(4).setPreferredWidth(75);
            table_note.getColumnModel().getColumn(4).setMaxWidth(100);
            table_note.getColumnModel().getColumn(5).setPreferredWidth(75);
            table_note.getColumnModel().getColumn(5).setMaxWidth(100);
            table_note.getColumnModel().getColumn(6).setPreferredWidth(75);
            table_note.getColumnModel().getColumn(6).setMaxWidth(100);
            table_note.getColumnModel().getColumn(7).setPreferredWidth(75);
            table_note.getColumnModel().getColumn(7).setMaxWidth(100);
            table_note.getColumnModel().getColumn(8).setPreferredWidth(75);
            table_note.getColumnModel().getColumn(8).setMaxWidth(100);
            table_note.getColumnModel().getColumn(9).setPreferredWidth(75);
            table_note.getColumnModel().getColumn(9).setMaxWidth(100);
            table_note.getColumnModel().getColumn(10).setPreferredWidth(75);
            table_note.getColumnModel().getColumn(10).setMaxWidth(100);
            table_note.getColumnModel().getColumn(11).setPreferredWidth(75);
            table_note.getColumnModel().getColumn(11).setMaxWidth(100);
            table_note.getColumnModel().getColumn(12).setPreferredWidth(75);
            table_note.getColumnModel().getColumn(12).setMaxWidth(100);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        combo_box_annee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_box_annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_box_anneeActionPerformed(evt);
            }
        });

        jLabel3.setText("Cycle :");

        combo_box_cycle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_box_cycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_box_cycleActionPerformed(evt);
            }
        });

        jLabel2.setText("Année :");

        jLabel4.setText("Classe :");

        combo_box_classe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_box_classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_box_classeActionPerformed(evt);
            }
        });

        jLabel7.setText("Type de matière :");

        combo_box_type_matiere_classe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_box_type_matiere_classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_box_type_matiere_classeActionPerformed(evt);
            }
        });

        jLabel5.setText("Matière :");

        combo_box_matiere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_box_matiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_box_matiereActionPerformed(evt);
            }
        });

        jLabel1.setText("Semestre :");

        combo_box_semestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_box_semestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_box_semestreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combo_box_cycle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_box_classe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_box_annee, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combo_box_type_matiere_classe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_box_matiere, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_box_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(combo_box_type_matiere_classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(combo_box_matiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(combo_box_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_box_annee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(combo_box_cycle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(combo_box_classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        button_bulletin_classe.setText("Bulletin classe");
        button_bulletin_classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bulletin_classeActionPerformed(evt);
            }
        });

        btn_actualiser_table.setForeground(new java.awt.Color(0, 153, 0));
        btn_actualiser_table.setText("Actualiser");
        btn_actualiser_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualiser_tableActionPerformed(evt);
            }
        });

        btn_calculer.setText("Calculer note");
        btn_calculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_actualiser_table, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_calculer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_bulletin_classe)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_bulletin_classe)
                    .addComponent(btn_calculer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_actualiser_table)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_pane_table_note)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll_pane_table_note, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo_box_anneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_box_anneeActionPerformed
        init_combo_box_semestre();
        init_combo_box_cycle();
        init_combo_box_classe();
        init_combo_box_type_matiere();
        init_combo_box_matiere();
    }//GEN-LAST:event_combo_box_anneeActionPerformed

    private void combo_box_cycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_box_cycleActionPerformed
        init_combo_box_classe();
        init_combo_box_type_matiere();
        init_combo_box_matiere();
    }//GEN-LAST:event_combo_box_cycleActionPerformed

    private void combo_box_classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_box_classeActionPerformed
        init_combo_box_type_matiere();
        init_combo_box_matiere();
    }//GEN-LAST:event_combo_box_classeActionPerformed

    private void combo_box_type_matiere_classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_box_type_matiere_classeActionPerformed
        init_combo_box_matiere();
        table_note();
    }//GEN-LAST:event_combo_box_type_matiere_classeActionPerformed

    private void combo_box_matiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_box_matiereActionPerformed
        table_note();
    }//GEN-LAST:event_combo_box_matiereActionPerformed

    private void combo_box_semestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_box_semestreActionPerformed
        table_note();
    }//GEN-LAST:event_combo_box_semestreActionPerformed

    private void menu_item_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_imprimerActionPerformed
        int row = table_note.getSelectedRow();
        if (row > -1 && combo_box_semestre.getSelectedIndex() > -1 && combo_box_classe.getSelectedIndex() > -1) {
            getBulletin(id_eleves.get(row), id_classes.get(combo_box_classe.getSelectedIndex()), id_semestres.get(combo_box_semestre.getSelectedIndex()));
        }
    }//GEN-LAST:event_menu_item_imprimerActionPerformed

    private void button_bulletin_classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bulletin_classeActionPerformed
        if (combo_box_classe.getSelectedIndex() < 0 || combo_box_classe.getSelectedItem().toString().equals("Toutes") || combo_box_semestre.getSelectedIndex() < 0 || table_note.getRowCount() < 1) {
            return;
        }
        getBulletin(null, id_classes.get(combo_box_classe.getSelectedIndex()), id_semestres.get(combo_box_semestre.getSelectedIndex()));
    }//GEN-LAST:event_button_bulletin_classeActionPerformed

    private void btn_actualiser_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualiser_tableActionPerformed
        table_note();

    }//GEN-LAST:event_btn_actualiser_tableActionPerformed

    private void btn_calculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculerActionPerformed
        calculer();
    }//GEN-LAST:event_btn_calculerActionPerformed
    private final HashMap<Integer, Long> id_eleves, id_matiere_classes, id_annees, id_cycles, id_classes, id_semestres, id_matieres, id_type_matieres;
    private final DefaultTableModel model;
    private final Long id_professeur;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualiser_table;
    private javax.swing.JButton btn_calculer;
    private javax.swing.JButton button_bulletin_classe;
    private javax.swing.JComboBox<String> combo_box_annee;
    private javax.swing.JComboBox<String> combo_box_classe;
    private javax.swing.JComboBox<String> combo_box_cycle;
    private javax.swing.JComboBox<String> combo_box_matiere;
    private javax.swing.JComboBox<String> combo_box_semestre;
    private javax.swing.JComboBox<String> combo_box_type_matiere_classe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem menu_item_imprimer;
    private javax.swing.JPopupMenu popup_menu;
    private javax.swing.JScrollPane scroll_pane_table_note;
    private javax.swing.JTable table_note;
    // End of variables declaration//GEN-END:variables
    private static void addPopup(Component component, final JPopupMenu popup) {
        component.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showMenu(e);
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showMenu(e);
                }
            }

            private void showMenu(MouseEvent e) {
                popup.show(e.getComponent(), e.getX(), e.getY());
            }
        });
    }

    private void popup() {
        addPopup(scroll_pane_table_note, popup_menu);
        addPopup(table_note, popup_menu);
    }

    private void init_combo_box_annee() {
        combo_box_annee.removeAllItems();
        id_annees.clear();
        try {
            ArrayList<bean.Annee> list = getController().getAnneeController().gets();
            if (list == null || list.isEmpty()) {
                return;
            }
            for (int i = 0; i < list.size(); i++) {
                combo_box_annee.addItem(list.get(i).getAnnee());
                id_annees.put(i, list.get(i).getId());
            }
        } catch (Exception e) {
            combo_box_annee.removeAllItems();
            id_annees.clear();
        }

    }

    private void init_combo_box_cycle() {
        combo_box_cycle.removeAllItems();
        id_cycles.clear();
        try {
            if (combo_box_annee.getSelectedIndex() < 0) {
                return;
            }
            Long id_annee;
            if (id_annees.get(combo_box_annee.getSelectedIndex()) != null) {
                id_annee = id_annees.get(combo_box_annee.getSelectedIndex());
            } else {
                return;
            }
            ArrayList<Cycle> list;
            if (getDroit().isProfesseur()) {
                list = getController().getCycleController().gets(id_annee, id_professeur);
            } else {
                list = getController().getCycleController().gets();
            }
            for (int i = 0; i < list.size(); i++) {
                combo_box_cycle.addItem(list.get(i).getCycle());
                id_cycles.put(i, list.get(i).getId());
            }
        } catch (Exception e) {
            combo_box_cycle.removeAllItems();
            id_cycles.clear();
        }
    }

    private void init_combo_box_classe() {
        combo_box_classe.removeAllItems();
        id_classes.clear();
        try {
            if (combo_box_annee.getSelectedIndex() < 0 || combo_box_cycle.getSelectedIndex() < 0) {
                return;
            }
            Long id_annee, id_cycle;
            if (id_annees.get(combo_box_annee.getSelectedIndex()) != null) {
                id_annee = id_annees.get(combo_box_annee.getSelectedIndex());
            } else {
                return;
            }
            if (id_cycles.get(combo_box_cycle.getSelectedIndex()) != null) {
                id_cycle = id_cycles.get(combo_box_cycle.getSelectedIndex());
            } else {
                return;
            }
            ArrayList<Classe> list;
            if (getDroit().isProfesseur()) {
                list = getController().getClasseController().gets(id_annee, id_cycle, id_professeur);
            } else {
                list = getController().getClasseController().gets(id_annee, id_cycle);
            }
            for (int i = 0; i < list.size(); i++) {
                combo_box_classe.addItem(list.get(i).getClasse());
                id_classes.put(i, list.get(i).getId());
            }
        } catch (Exception e) {
            combo_box_classe.removeAllItems();
            id_classes.clear();
        }
    }

    private void init_combo_box_type_matiere() {
        combo_box_type_matiere_classe.removeAllItems();
        id_type_matieres.clear();
        if (combo_box_annee.getSelectedIndex() < 0 || combo_box_cycle.getSelectedIndex() < 0 || combo_box_classe.getSelectedIndex() < 0) {
            return;
        }
        Long id_classe;
        try {
            if (id_classes.get(combo_box_classe.getSelectedIndex()) != null) {
                id_classe = id_classes.get(combo_box_classe.getSelectedIndex());
            } else {
                return;
            }
            ArrayList<MatiereType> list;
            if (getDroit().isProfesseur()) {
                list = getController().getMatiereTypeController().gets(id_classe, id_professeur);
            } else {
                list = getController().getMatiereTypeController().gets();
            }
            for (int i = 0; i < list.size(); i++) {
                combo_box_type_matiere_classe.addItem(list.get(i).getType());
                id_type_matieres.put(i, list.get(i).getId());
            }
        } catch (Exception e) {
            combo_box_type_matiere_classe.removeAllItems();
            id_type_matieres.clear();
        }
    }

    private void init_combo_box_matiere() {
        combo_box_matiere.removeAllItems();
        id_matieres.clear();
        if (combo_box_annee.getSelectedIndex() < 0 || combo_box_cycle.getSelectedIndex() < 0 || combo_box_classe.getSelectedIndex() < 0 || combo_box_type_matiere_classe.getSelectedIndex() < 0) {
            return;
        }
        Long id_matiere_type, id_classe, id_cycle;
        try {
            if (id_cycles.get(combo_box_cycle.getSelectedIndex()) != null) {
                id_cycle = id_cycles.get(combo_box_cycle.getSelectedIndex());
            } else {
                return;
            }
            if (id_classes.get(combo_box_classe.getSelectedIndex()) != null) {
                id_classe = id_classes.get(combo_box_classe.getSelectedIndex());
            } else {
                return;
            }
            if (id_type_matieres.get(combo_box_type_matiere_classe.getSelectedIndex()) != null) {
                id_matiere_type = id_type_matieres.get(combo_box_type_matiere_classe.getSelectedIndex());
            } else {
                return;
            }
            ArrayList<MatiereClasse> list;
            if (getDroit().isProfesseur()) {
                list = getController().getMatiereClasseController().gets(null, id_matiere_type, id_classe, id_cycle, id_professeur);
            } else {
                list = getController().getMatiereClasseController().gets(null, id_matiere_type, id_classe, id_cycle);

            }
            ArrayList<Matiere> list_matiere = new ArrayList<>();
            list.forEach((i) -> {
                list_matiere.add(getController().getMatiereController().get(i.getId_matiere()));
            });
            for (int i = 0; i < list_matiere.size(); i++) {
                combo_box_matiere.addItem(list_matiere.get(i).getMatiere());
                id_matieres.put(i, list_matiere.get(i).getId());
            }
        } catch (Exception e) {
            combo_box_matiere.removeAllItems();
            id_matieres.clear();
        }
    }

    private void init_combo_box_semestre() {
        combo_box_semestre.removeAllItems();
        id_semestres.clear();
        ArrayList<Semestre> list = getController().getSemestreController().gets();
        if (list == null) {
            return;
        }
        try {
            for (int i = 0; i < list.size(); i++) {
                combo_box_semestre.addItem(list.get(i).getSemestre());
                id_semestres.put(i, list.get(i).getId());
            }
        } catch (Exception e) {
            combo_box_semestre.removeAllItems();
            id_semestres.clear();
        }
    }

    private void init_model() {
        model.setRowCount(0);
    }

    private void table_note() {
        Thread thread = new Thread(() -> {
            init_model();
            id_eleves.clear();
            id_matiere_classes.clear();
            if (combo_box_type_matiere_classe.getSelectedIndex() < 0 || combo_box_annee.getSelectedIndex() < 0 || combo_box_cycle.getSelectedIndex() < 0 || combo_box_classe.getSelectedIndex() < 0 || combo_box_matiere.getSelectedIndex() < 0 || combo_box_semestre.getSelectedIndex() < 0) {
                return;
            }
            try {
                Long id_annee = id_annees.get(combo_box_annee.getSelectedIndex());
                Long id_cycle = id_cycles.get(combo_box_cycle.getSelectedIndex());
                Long id_classe = id_classes.get(combo_box_classe.getSelectedIndex());
                Long id_matiere = id_matieres.get(combo_box_matiere.getSelectedIndex());
                Long id_semestre = id_semestres.get(combo_box_semestre.getSelectedIndex());
                ArrayList<bean.Note> list = getController().getEvaluationMatiereController().gets(id_annee, id_cycle, id_classe, id_matiere);
                if (list == null) {
                    return;
                }
                for (int i = 0; i < list.size(); i++) {
                    EvaluationMatiere evaluationMatiere = getController().getEvaluationMatiereController().get(list.get(i).getId_eleve(), list.get(i).getId_matiere_classe(), id_semestre);
                    Object row[] = new Object[13];
                    row[0] = i + 1;
                    row[1] = list.get(i).getNom_prenom();
                    if (evaluationMatiere != null) {
                        row[2] = evaluationMatiere.getInterro_1() > -1.00 ? evaluationMatiere.getInterro_1() : "";
                        row[3] = evaluationMatiere.getInterro_2() > -1.00 ? evaluationMatiere.getInterro_2() : "";
                        row[4] = evaluationMatiere.getInterro_3() > -1.00 ? evaluationMatiere.getInterro_3() : "";
                        row[5] = evaluationMatiere.getInterro_4() > -1.00 ? evaluationMatiere.getInterro_4() : "";
                        row[6] = evaluationMatiere.getMoyenne_interro() > -1.00 ? evaluationMatiere.getMoyenne_interro() : "";
                        row[7] = evaluationMatiere.getDevoir_1() > -1.00 ? evaluationMatiere.getDevoir_1() : "";
                        row[8] = evaluationMatiere.getDevoir_2() > -1.00 ? evaluationMatiere.getDevoir_2() : "";
                        row[9] = evaluationMatiere.getMoyenne_devoir() > -1.00 ? evaluationMatiere.getMoyenne_devoir() : "";
                        row[10] = evaluationMatiere.getComposition() > -1.00 ? evaluationMatiere.getComposition() : "";
                        row[11] = evaluationMatiere.getMoyenne_classe() > -1.00 ? evaluationMatiere.getMoyenne_classe() : "";
                        row[12] = evaluationMatiere.getMoyenne() > -1.00 ? evaluationMatiere.getMoyenne() : "";
                    } else {
                        row[2] = "";
                        row[3] = "";
                        row[4] = "";
                        row[5] = "";
                        row[6] = "";
                        row[7] = "";
                        row[8] = "";
                        row[9] = "";
                        row[10] = "";
                        row[11] = "";
                        row[12] = "";
                    }
                    id_eleves.put(i, list.get(i).getId_eleve());
                    id_matiere_classes.put(i, list.get(i).getId_matiere_classe());
                    model.addRow(row);
                }
                table_note.setModel(model);
                if (table_note.getColumnModel().getColumnCount() > 0) {
                    table_note.getColumnModel().getColumn(0).setPreferredWidth(35);
                    table_note.getColumnModel().getColumn(0).setMaxWidth(35);
                    table_note.getColumnModel().getColumn(1).setPreferredWidth(250);
                    table_note.getColumnModel().getColumn(1).setMaxWidth(300);
                    table_note.getColumnModel().getColumn(2).setPreferredWidth(75);
                    table_note.getColumnModel().getColumn(2).setMaxWidth(100);
                    table_note.getColumnModel().getColumn(3).setPreferredWidth(75);
                    table_note.getColumnModel().getColumn(3).setMaxWidth(100);
                    table_note.getColumnModel().getColumn(4).setPreferredWidth(75);
                    table_note.getColumnModel().getColumn(4).setMaxWidth(100);
                    table_note.getColumnModel().getColumn(5).setPreferredWidth(75);
                    table_note.getColumnModel().getColumn(5).setMaxWidth(100);
                    table_note.getColumnModel().getColumn(6).setPreferredWidth(75);
                    table_note.getColumnModel().getColumn(6).setMaxWidth(100);
                    table_note.getColumnModel().getColumn(7).setPreferredWidth(75);
                    table_note.getColumnModel().getColumn(7).setMaxWidth(100);
                    table_note.getColumnModel().getColumn(8).setPreferredWidth(75);
                    table_note.getColumnModel().getColumn(8).setMaxWidth(100);
                    table_note.getColumnModel().getColumn(9).setPreferredWidth(75);
                    table_note.getColumnModel().getColumn(9).setMaxWidth(100);
                    table_note.getColumnModel().getColumn(10).setPreferredWidth(75);
                    table_note.getColumnModel().getColumn(10).setMaxWidth(100);
                    table_note.getColumnModel().getColumn(11).setPreferredWidth(75);
                    table_note.getColumnModel().getColumn(11).setMaxWidth(100);
                    table_note.getColumnModel().getColumn(12).setPreferredWidth(75);
                    table_note.getColumnModel().getColumn(12).setMaxWidth(100);
                    table_note.setShowVerticalLines(true);
                    table_note.setShowHorizontalLines(true);
                    table_note.setRowHeight(30);
                    table_note.setGridColor(Color.BLACK);
                    table_note.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                    table_note.getModel().addTableModelListener((TableModelEvent e) -> {
                        int row = table_note.getSelectedRow();
                        if (row < 0) {
                            return;
                        }
                        int column = table_note.getSelectedColumn();
                        String columName = table_note.getModel().getColumnName(column);
                        try {
                            mise_a_jour_note(row, columName, table_note.getValueAt(row, column).toString());
                        } catch (ArrayIndexOutOfBoundsException ex) {
                            table_note();
                        }

                    });
                }
            } catch (Exception e) {
                model.setRowCount(0);
                id_eleves.clear();
                id_matiere_classes.clear();
            }
        });
        thread.setPriority(Thread.MAX_PRIORITY);
        thread.start();
    }

    private void mise_a_jour_note(int row, String columName, String valeur_string) {
        try {
            Long id_semestre;
            if (combo_box_semestre.getSelectedIndex() < 0) {
                return;
            }
            if (id_semestres.get(combo_box_semestre.getSelectedIndex()) != null) {
                id_semestre = id_semestres.get(combo_box_semestre.getSelectedIndex());
            } else {
                return;
            }
            Long id_eleve = id_eleves.get(row), id_matiere_classe = id_matiere_classes.get(row);
            EvaluationMatiere evaluationMatiere = getController().getEvaluationMatiereController().get(id_eleve, id_matiere_classe, id_semestre);
            /*
             * supression d'une note
             */
            if (valeur_string.isEmpty() && evaluationMatiere != null) {
                switch (combo_box_semestre.getSelectedItem().toString()) {
                    case "S1" -> {
                        if (!getDroit().isS1()) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de saisie S1 réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    }
                    case "S2" -> {
                        if (!getDroit().isS2()) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de saisie S2 réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    }
                    default -> {
                        JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de saisie Semestre réquis ", JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }
                }
                switch (columName) {
                    case "Interro. N°1" -> {
                        if (!getDroit().isSuprimer() && evaluationMatiere.getInterro_1() != -1.00) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de supression réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        getController().getEvaluationMatiereController().remove(id_eleve, id_matiere_classe, id_semestre, "interro_1");
                    }
                    case "Interro. N°2" -> {
                        if (!getDroit().isSuprimer() && evaluationMatiere.getInterro_2() != -1.00) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de supression réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        getController().getEvaluationMatiereController().remove(id_eleve, id_matiere_classe, id_semestre, "interro_2");
                    }
                    case "Interro. N°3" -> {
                        if (!getDroit().isSuprimer() && evaluationMatiere.getInterro_3() != -1.00) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de supression réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        getController().getEvaluationMatiereController().remove(id_eleve, id_matiere_classe, id_semestre, "interro_3");
                    }
                    case "Interro. N°4" -> {
                        if (!getDroit().isSuprimer() && evaluationMatiere.getInterro_4() != -1.00) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de supression réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        getController().getEvaluationMatiereController().remove(id_eleve, id_matiere_classe, id_semestre, "interro_4");
                    }
                    case "Devoir N°1" -> {
                        if (!getDroit().isSuprimer() && evaluationMatiere.getDevoir_1() != -1.00) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de supression réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        getController().getEvaluationMatiereController().remove(id_eleve, id_matiere_classe, id_semestre, "devoir_1");
                    }
                    case "Devoir N°2" -> {
                        if (!getDroit().isSuprimer() && evaluationMatiere.getDevoir_2() != -1.00) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de supression réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        getController().getEvaluationMatiereController().remove(id_eleve, id_matiere_classe, id_semestre, "devoir_2");
                    }
                    case "Composition" -> {
                        if (!getDroit().isSuprimer() && evaluationMatiere.getComposition() != -1.00) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de supression réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        getController().getEvaluationMatiereController().remove(id_eleve, id_matiere_classe, id_semestre, "composition");
                    }
                    default -> {
                    }
                }
                return;
            } else if (valeur_string.isEmpty() && evaluationMatiere == null) {
                return;
            }
            /*fin supression d'une note*/
            //Ajout et modification d'une note
            Double valeur;
            try {
                valeur = Double.valueOf(valeur_string);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valeur incorrect !\nSaisissez uniquement des chiffres !\nMettre un point a la place de virgule.", "Valeur incorrecte ", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if ((valeur < 0.00 || valeur > 10.00) && columName.contains("Interro.")) {
                JOptionPane.showMessageDialog(this, "Valeur incorrect !\nLa note d'interrogation doit être incluse entre 0 et 10!", "Valeur incorrecte ", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (valeur < 0.00 || valeur > 20.00) {
                JOptionPane.showMessageDialog(this, "Valeur incorrect !\nLa note à saisir doit être incluse entre 0 et 20!", "Valeur incorrecte ", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (evaluationMatiere == null) {
                switch (combo_box_semestre.getSelectedItem().toString()) {
                    case "S1" -> {
                        if (!getDroit().isS1()) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de saisie S1 réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    }
                    case "S2" -> {
                        if (!getDroit().isS2()) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de saisie S2 réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    }
                    default -> {
                        JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de saisie Semestre réquis ", JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }
                }
                if (!getDroit().isAjouter()) {
                    JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
            switch (combo_box_semestre.getSelectedItem().toString()) {
                case "S1" -> {
                    if (!getDroit().isS1()) {
                        JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de saisie S1 réquis ", JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }
                }
                case "S2" -> {
                    if (!getDroit().isS2()) {
                        JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de saisie S2 réquis ", JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }
                }
                default -> {
                    JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit de saisie Semestre réquis ", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
            switch (columName) {
                case "Interro. N°1" -> {
                    if (evaluationMatiere == null) {
                        if (!getDroit().isAjouter()) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    } else {
                        if (!getDroit().isAjouter() && (evaluationMatiere.getInterro_1() == -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        if (!getDroit().isModifier() && (evaluationMatiere.getInterro_1() != -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    }
                    getController().getEvaluationMatiereController().add(id_eleve, id_matiere_classe, id_semestre, "interro_1", valeur);
                }
                case "Interro. N°2" -> {
                    if (evaluationMatiere == null) {
                        if (!getDroit().isAjouter()) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    } else {
                        if (!getDroit().isAjouter() && (evaluationMatiere.getInterro_2() == -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        if (!getDroit().isModifier() && (evaluationMatiere.getInterro_2() != -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    }
                    getController().getEvaluationMatiereController().add(id_eleve, id_matiere_classe, id_semestre, "interro_2", valeur);
                }
                case "Interro. N°3" -> {
                    if (evaluationMatiere == null) {
                        if (!getDroit().isAjouter()) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    } else {
                        if (!getDroit().isAjouter() && (evaluationMatiere.getInterro_3() == -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        if (!getDroit().isModifier() && (evaluationMatiere.getInterro_3() != -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    }
                    getController().getEvaluationMatiereController().add(id_eleve, id_matiere_classe, id_semestre, "interro_3", valeur);
                }
                case "Interro. N°4" -> {
                    if (evaluationMatiere == null) {
                        if (!getDroit().isAjouter()) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    } else {
                        if (!getDroit().isAjouter() && (evaluationMatiere.getInterro_4() == -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        if (!getDroit().isModifier() && (evaluationMatiere.getInterro_4() != -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    }
                    getController().getEvaluationMatiereController().add(id_eleve, id_matiere_classe, id_semestre, "interro_4", valeur);
                }
                case "Devoir N°1" -> {
                    if (evaluationMatiere == null) {
                        if (!getDroit().isAjouter()) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    } else {
                        if (!getDroit().isAjouter() && (evaluationMatiere.getDevoir_1() == -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        if (!getDroit().isModifier() && (evaluationMatiere.getDevoir_1() != -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    }
                    getController().getEvaluationMatiereController().add(id_eleve, id_matiere_classe, id_semestre, "devoir_1", valeur);
                }
                case "Devoir N°2" -> {
                    if (evaluationMatiere == null) {
                        if (!getDroit().isAjouter()) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    } else {
                        if (!getDroit().isAjouter() && (evaluationMatiere.getDevoir_2() == -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        if (!getDroit().isModifier() && (evaluationMatiere.getDevoir_2() != -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    }
                    getController().getEvaluationMatiereController().add(id_eleve, id_matiere_classe, id_semestre, "devoir_2", valeur);
                }
                case "Composition" -> {
                    if (evaluationMatiere == null) {
                        if (!getDroit().isAjouter()) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    } else {
                        if (!getDroit().isAjouter() && (evaluationMatiere.getComposition() == -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                        if (!getDroit().isModifier() && (evaluationMatiere.getComposition() != -1.00)) {
                            JOptionPane.showMessageDialog(this, "Contacter l'administration pour cette action.", "Droit d'ajout réquis ", JOptionPane.INFORMATION_MESSAGE);
                            return;
                        }
                    }
                    getController().getEvaluationMatiereController().add(id_eleve, id_matiere_classe, id_semestre, "composition", valeur);
                }
                default -> {
                }
            }
        } catch (HeadlessException e) {
        }
    }

    private void getBulletin(Long id_eleve, Long id_classe, Long id_semestre) {
        if (combo_box_annee.getSelectedIndex() < 0 || combo_box_cycle.getSelectedIndex() < 0 || combo_box_classe.getSelectedIndex() < 0 || combo_box_matiere.getSelectedIndex() < 0 || combo_box_semestre.getSelectedIndex() < 0) {
            return;
        }
        ArrayList<EvaluationClasse> list = getController().getEvaluationClasseController().gets(id_eleve, id_classe, id_semestre);
        try {
            HashMap<String, Object> m = new HashMap<>();
            String reports = System.getProperty("user.dir") + "\\ressources\\report\\BULLETIN_RELEASE.jasper";
            m.put("id_classe", id_classe);
            m.put("id_semestre", id_semestre);
            m.put("id_eleve", list.get(0).getId_eleve());
            JasperPrint jasperPrint = JasperFillManager.fillReport(reports, m, getConnection());
            if (list.size() > 1) {
                for (int i = 1; i < list.size(); i++) {
                    HashMap<String, Object> mp = new HashMap<>();
                    mp.put("id_classe", id_classe);
                    mp.put("id_semestre", id_semestre);
                    mp.put("id_eleve", list.get(i).getId_eleve());
                    try {
                        JasperPrint jasperPrint1 = JasperFillManager.fillReport(reports, mp, getConnection());
                        jasperPrint.addPage(jasperPrint1.getPages().get(0));
                    } catch (JRException ex) {
                        Logger.getLogger(NotePanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, " Echec d'impression du Rélévé de note\n" + ex.getMessage());
        } catch (IndexOutOfBoundsException e) {
        }
    }

    private void calculer() {
        if (combo_box_annee.getSelectedIndex() < 0 || combo_box_cycle.getSelectedIndex() < 0 || combo_box_classe.getSelectedIndex() < 0 || combo_box_semestre.getSelectedIndex() < 0) {
            return;
        }
        Long id_annee = id_annees.get(combo_box_annee.getSelectedIndex());
        Long id_cycle = id_cycles.get(combo_box_cycle.getSelectedIndex());
        Long id_classe = id_classes.get(combo_box_classe.getSelectedIndex());
        Long id_semestre = id_semestres.get(combo_box_semestre.getSelectedIndex());
        getController().getMatiereClasseController().gets(null, null, id_classe, id_cycle).forEach((matiereClasse) -> {
            Matiere matiere = getController().getMatiereController().get(matiereClasse.getId_matiere());
            getController().getEvaluationMatiereController().update_coefficient(matiereClasse.getId());
            getController().getEleveClasseController().gets(null, id_annee, id_cycle, id_classe, null, null, null).forEach((ec) -> {
                getController().getEvaluationMatiereController().update(ec.getId_eleve(), matiereClasse.getId(), id_semestre);
                getController().getEvaluationMatiereTypeController().update(ec.getId_eleve(), id_classe, matiere.getId_matiere_type(), id_semestre);
                getController().getEvaluationClasseController().update(ec.getId_eleve(), id_classe, id_semestre);
            });
            getController().getEvaluationMatiereController().update(matiereClasse.getId(), id_semestre);
        });
        getController().getMatiereTypeController().gets().forEach((matiereType) -> {
            getController().getEvaluationMatiereTypeController().update(id_classe, matiereType.getId(), id_semestre);
        });
        getController().getEvaluationClasseController().update(id_classe, id_semestre);
        JOptionPane.showMessageDialog(this, "Opération effectuée avec success ", "Réussie !", JOptionPane.INFORMATION_MESSAGE);
    }
}
